services:
  postgres:
    image: postgres:14
    container_name: schedulify-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: schedulify
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 